{% set python_min = "3.10" %}
{% set name = "ansys-tools-visualization-interface" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_tools_visualization_interface-{{ version }}.tar.gz
  sha256: b1ff45fd3027d645ca4d20eda1de151e12caced9cb88521a2107a25924c218c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pyvista >=0.43.0,<1
    - beartype >=0.17.0,<1
    - websockets >=12.0,<16
    - trame >=3.6.0,<4
    - trame-vtk >=2.8.7,<3
    - trame-vuetify >=2.4.3,<3

test:
  imports:
    - ansys.tools.visualization_interface
  commands:
  # Disabled until https://github.com/conda-forge/vtk-feedstock/pull/324 is solved
  #   - pip check
    - pip list
    - python -c "from ansys.tools.visualization_interface import __version__; print(__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Python visualization interface for PyAnsys libraries
  home: https://visualization-interface.tools.docs.pyansys.com/
  dev_url: https://github.com/ansys/ansys-tools-visualization-interface
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobPasMue
    - AlejandroFernandezLuces
